### ISSUE TITLE
Bump kysely-codegen to v0.7.x

### ISSUE THREAD

**Issue by dulciejackson** [serverless-stack/sst#2149] opened 2022-10-19 13:43 UTC
Right now, `@serverless-stack/core` uses `kysely-codegen@^0.6.0`.
The `kysely-codegen` team have just released v0.7.0, which adds functionality for enum typegen as mentioned in [this issue](https://github.com/RobinBlomberg/kysely-codegen/issues/21).

Since the new release is a breaking change, some work needs to be done internally to SST to ensure that `kysely-codegen` can be used as expected - a manual resolution breaks so there must be some incompatibilities.

I've tried looking at this myself, but came across some problems and I don't have a deep enough knowledge of the interdependencies here to fix it confidently!

**Comment by fwang** [comment] 2022-12-14 04:52
Thanks @dulciejackson. Added to the roadmap. Will prioritize.

**Comment by rosinbum** [comment] 2022-12-14 14:37
For users of SST who need the issue resolved prior to a new release, add a package overwrite to the `package.json`. This resolves issues caused by the miss match versions of `krsely` and `krsely-codegen`. Just remember to remove it when there is a new release of SST that resolves the issue. Below is the block I added.

```
"overrides": {
    "@serverless-stack/core": {
      "kysely": "^0.22",
      "kysely-codegen": "^0.8",
      "kysely-data-api": "^0.1.4"
    },
    "@serverless-stack/resources": {
      "kysely": "^0.22",
      "kysely-codegen": "^0.8",
      "kysely-data-api": "^0.1.4"
    }
  },
```

**Comment by thdxr** [comment] 2022-12-19 16:41
Fixed in v2

**Closed by thdxr** 2022-12-19 16:41 UTC
Labels: bug
