### ISSUE TITLE
Rate exceeded throttling error from CDK commands

### ISSUE THREAD

**Issue by fwang** [serverless-stack/sst#1876] opened 2022-07-12 16:40 UTC
Here's what's going on behind the scene you run sst start/deploy:
1. SST builds and figures out all the Stack in ur App, and in what order to deploy them based on dependencies.
2. SST calls cdk deploy to start the deployment process
3. SST periodically polls for the Stack update status every 5 seconds and wait for the update to complete.

In Step 3, SST actually indefinitely retries on Throttling errors.
The failure actually came from step 2. cdk deploy does a CloudFormation DescribeStack call internally, and errors out on Throttling errors.

---
Requests:
- Kos https://discord.com/channels/983865673656705025/994990122464448592

**Comment by lkow** [comment] 2022-10-17 10:37
@fwang any ETA for this? Started receiving throttling errors recently (caused by DescribeStack like in the description) when we grew both in Stacks per App and headcount

**Comment by fwang** [comment] 2022-10-17 11:51
@lkow lemme check w/ @thdxr as we are re-writing the CLI, and this might be fix-able.

Dax, given we are importing CDK now, can we override the AWS SDK's inside CDK's code?

**Comment by thdxr** [comment] 2022-12-19 16:42
Fixed in v2

**Closed by thdxr** 2022-12-19 16:42 UTC
Labels: enhancement
